### ISSUE TITLE
Unify efforts with BQ datasketches repository

### ISSUE THREAD

**Issue by davecromberge** [apache/datasketches-bigquery#4]
We have shared this repository with some Google engineers.  They were unaware of its existence and have created their own repository with similar objectives.  

For example, a recent pull request introduces KLL, Tuple and Theta support to BigQuery:
https://github.com/GoogleCloudPlatform/bigquery-utils/pull/423

Furthermore, they have used a different method for assembling the scripts than what is used in this repository.  This introduces additional complexity but avoids potential problems with memory exhaustion.

Is it worth consolidating efforts?

**Comment by AlexanderSaydakov** [comment]
We are not entirely sure yet how to consolidate efforts. We can try to contribute to Google repo.
On the other hand, they don't seem to have any versioning there, and the datasketches related SQL stuff is mixed with other UDFs. We know how to do Apache process with community voting and semantic versioning. We may want to keep this repo anyway. Let's discuss.

**Comment by leerho** [comment]
@davecromberge,
We have made progress.  Google BQ has agreed to use this repo for development and they will bring in the adaptors based on release tags.  There are some more details to work out but this is big progress.

**Comment by davecromberge** [comment]
@leerho thank you for the update - this is great news.  Should I keep the issue open or should we mark it as resolved?

My team is interested primarily in the CPC and Theta sketches in the BQ environment and would be available to deploy early versions to help with testing at scale if you would find this helpful.

**Comment by leerho** [comment]
Hi David,

Thanks for the offer, we just might ask for some help in testing!

Cheers,
Lee.
