### ISSUE TITLE
change theta sketch function names conflicting with bqutils repo

### ISSUE THREAD

**Issue by nikunjbhartia** [apache/datasketches-bigquery#78]
We need to ensure that there are no function name conflicts with existing sketch functions in bqutils repo. 

There are 3 conflicting theta sketch functions in this repo: 
https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs/datasketches#theta-sketch

1) theta_sketch_union
2) theta_sketch_intersection
3) theta_sketch_a_not_b

**Comment by AlexanderSaydakov** [comment]
Is this necessary if the whole set of Apache Datasketches functions would be deployed to its own dataset?

The motivation for these function names was to have all functions for a particular sketch share the same prefix, which is "theta_sketch" in this case.

If we really have to rename them, I would suggest:
theta_union
theta_intersection
theta_a_not_b

**Comment by nikunjbhartia** [comment]
Let me discuss internally and get back.

**Comment by AlexanderSaydakov** [comment]
As I understand, the plan is to deploy Apache Datasketches functions to a separate dataset.
Should we close this issue?

**Comment by nikunjbhartia** [comment]
You are right, closing this.
