### ISSUE TITLE
change gs://$JS_BUCKET reference to ${JS_BUCKET}

### ISSUE THREAD

**Issue by nikunjbhartia** [apache/datasketches-bigquery#79]
bqutils repo deployment framework require JS_BUCKET referenced as ${JS_BUCKET} where the JS_BUCKET env variable should have gs://prefix 

eg: https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/community/theta_sketch_int64.sqlx#L22

Current repo uses the reference: gs://$JS_BUCKET

**Comment by AlexanderSaydakov** [comment]
done
